---
title: "Endosymbiont Density (cell counts) Analysis"
author: "Author: Emma Strand; emma_strand@uri.edu"
output:
  github_document: default
  pdf_document:
    keep_tex: yes
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages.
```{r}
rm(list=ls())

library(plyr)
library(dplyr)
library(readxl)
library(tidyr)
library(tidyverse)
library(ggpubr)
library(purrr)
library(Rmisc)
library(lme4)
library(car)
library(sjPlot)
library(ggstatsplot)
library(emmeans)
library(Rmisc)
```

## Load in data  

```{r}
meta <- read_excel("Dec-July-2019-analysis/data/Physiology-URI-labwork.xlsx", sheet = "Master-ID-List")
data <- read_excel("Dec-July-2019-analysis/data/Physiology-URI-labwork.xlsx", sheet = "Counts")
sa <- read_excel("Dec-July-2019-analysis/data/Physiology-URI-labwork.xlsx", sheet = "Surface_area")

df <- full_join(meta, data, by = c("ColonyID", "Date")) 
df <- full_join(df, sa, by = c("ColonyID", "Date"))

df$ColonyID <- as.character(df$ColonyID)
df$Date <- as.character(df$Date)
```

## Calculate surface area 

```{r}
# Standard curve
st <- read_excel("Dec-July-2019-analysis/data/Wax_Dipping_Curve_091522.xlsx")
st$delta <- st$Wax_Weight-st$Weight1

stnd.curve <- lm(Surface_Area~delta, data=st)
plot(Surface_Area~delta, data=st)
stnd.curve$coefficients
summary(stnd.curve) #R2 = 0.9448

# Calculate surface area
sa$delta <- sa$Weight2-sa$Weight1
df$SA <- stnd.curve$coefficients[2] * sa$delta + stnd.curve$coefficients[1]

ggplot(data=st, aes(x=delta, y=Surface_Area)) + theme_bw() +
  geom_point() +
  geom_point(data=df, aes(x=sa$delta, y=SA), color="blue")
```


## Calculate mean cell count per sample 

```{r}
df <- df %>%
  gather("rep", "count", Count1, Count2, Count3, Count4, Count5, Count6) %>%
  dplyr::group_by(ColonyID, Date) %>%
  mutate(count_mean = mean(count),
         cells.mL = count_mean * 10000 / `Squares counted`,
         cells = cells.mL * `volume (mL)`, 
         haemo.cells.cm2 = cells / SA) %>%
  ungroup() %>%
  filter(!is.na(cells)) %>%
  select(ColonyID, Date, Bleach, `volume (mL)`, count_mean, cells.mL, cells, haemo.cells.cm2, SA) %>%
  distinct() %>%
  write_csv(., file = "Dec-July-2019-analysis/data/cell_counts.csv")

df2 <- summarySE(df, measurevar = c("haemo.cells.cm2"), groupvars = c("Date", "Bleach"))
```

## Visualize data

```{r}
df %>%
  ggplot(., aes(x=Bleach, y=haemo.cells.cm2, color=Bleach)) + 
  theme_classic() + xlab("") +
  geom_boxplot() +
  geom_point() +
  facet_grid(~Date)

df2 %>%
  ggplot(., aes(x=Date, y=haemo.cells.cm2, color=Bleach)) + 
  geom_errorbar(aes(ymin=haemo.cells.cm2-se, ymax=haemo.cells.cm2+se), size=0.8, width=.1) +
  theme_classic() + xlab("") + geom_point(size=4) +
  geom_line(aes(group = Bleach), size=0.8)

df %>%
  ggplot(., aes(x=Date, y=haemo.cells.cm2, color=Bleach)) +
  theme_classic() + xlab("") +
  geom_point() + geom_line(aes(group = ColonyID), size=0.8) +
  facet_grid(~Bleach)
```

