---
title: "Surface Area Analysis"
author: "EL Strand"
output:
  html_document:
    toc: yes
    toc_depth: 6
    toc_float: yes
  pdf_document:
    keep_tex: yes
editor_options: 
  chunk_output_type: console
---

Script to analyze surface area for the Mcap 2021 Symbiont Integration project.  

# **Setup**  

Set up workspace, set options, and load required packages.    
```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# **Load packages** 

```{r}
# load packages
library(tidyverse)
library(ggplot2)
```

# **Create standard curve**

```{r}
# Load in dataframe
standards <- read.csv("Dec-July-2019-analysis/data/Wax_dipping_standards.csv", header = TRUE)

# Calculate the delta mass (pre wax dip, post wax dip)
standards$delta.mass.g <- standards$weight2.g-standards$weight1.g

# Take out standard 1 and 8 
standards <- standards %>% filter(!Standard == "Standard8") %>% filter(!Standard == "Standard1") 

# calculate the curve coefficients for slope and intercept to apply as the standard
stnd.curve <- lm(Surface_area_mm~delta.mass.g, data=standards)

standards %>% ggplot(aes(x=delta.mass.g, y=Surface_area_mm)) + theme_bw() + 
  geom_jitter(width = 0.05) + ylab("Surface area (mm^2)") +
  geom_smooth(method='lm') 

stnd.curve$coefficients
summary(stnd.curve)$r.squared
```




